#!/usr/bin/env python3

import os, re, argparse
from subprocess import check_output

destdir="src"
srcdir="raw"
out2html = True

def generate_site():
    # Add ". mso zh.tmac" for each translated file
    ChineseSupport = ''

    if not os.path.exists(groffdir):
        print("Please generate the groff files using ./generate --groff first.")
        return

    for root, dirs, files in os.walk(destdir):
        if "man" in root:
            for filename in files:
                if re.match(".*\.[1-9]", filename):
                    ifilepath = root + "/" + filename
                    htmlpath = ifilepath.replace(destdir+"/", sitedir, 1) + ".html"
                    htmldir = root.replace(destdir+"/", sitedir, 1)
                    file = open(ifilepath, 'r')
                    firstLine = file.readline()
                    remainingLines = file.readlines()
                    file.close()

                    if firstLine != ChineseSupport:
                        file = open(ifilepath, 'w')
                        file.write(ChineseSupport)
                        file.write(firstLine)
                        file.write("".join(remainingLines))
                        file.close()
                        print("[groff] " + ifilepath)

                    check_output(["mkdir", "-p", htmldir])
                    output = check_output(["man2html", ifilepath], universal_newlines=True)
                    file = open(htmlpath, "w")
                    file.write(output)
                    file.close()
                    print("[html] " + htmlpath)

    for root, dirs, files in os.walk(srcdir):
        if "man" in root:
            for filename in files:
                if re.match(".*\.[1-9]", filename):
                    ifilepath = root + "/" + filename
                    htmlpath = sitedir + ifilepath.replace("raw/man", srcdir) + ".html"
                    htmldir = sitedir + root.replace("raw/man", srcdir)
                    file = open(ifilepath, 'r')
                    firstLine = file.readline()
                    remainingLines = file.readlines()
                    file.close()

                    check_output(["mkdir", "-p", htmldir])
                    output = check_output(["man2html", ifilepath], universal_newlines=True)
                    file = open(htmlpath, "w")
                    file.write(output)
                    file.close()
                    print("[html] " + htmlpath)

def generate_groff():
    poconf = "[po4a_langs] zh_CN\n"
    poconf = poconf + "[po4a_paths] template/$master.pot $lang:po/$master.$lang.po\n"
    poconfpath = "/tmp/po.conf"
    for root, dirs, files in os.walk(srcdir):
        if "man" in root:
            for filename in files:
                if re.match(".*\.[1-9]", filename):
                    ifilepath = root+"/"+filename
                    # jump over those one-line manpages
                    with open(ifilepath) as ifile:
                        if (len(ifile.readlines()) == 1):
                            continue
                    poconf = poconf + "[type: man] " + ifilepath + " zh_CN:"
                    poconf = poconf + ifilepath.replace(srcdir, destdir)
                    poconf = poconf + ' opt:"-L UTF-8 -M UTF-8"' + "\n"

    poconffd = open(poconfpath, "w")
    poconffd.write(poconf)
    poconffd.close()
    print(check_output(["po4a", "-o", "untranslated=MT,ME", "-o", "groff_code=translate",poconfpath], universal_newlines=True))

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Generate the translated groff and/or html files")
    parser.add_argument('--groff', action="store_true",
                        help='Generate the translated groff files to ./src')
    parser.add_argument('--site', action="store_true",
                        help='Generate the site to ../man-pages-zh.github.io/')
    args = parser.parse_args()
    if args.groff:
        generate_groff()
    if args.site:
        generate_html()
        
    if not args.groff and not args.site:
        parser.print_help()
