#!/bin/bash

# get command name from arguments
if [ "x$1" = "x" ]; then
    echo "Invalid argument."
    exit 1
fi
CMD=$1

# check if po4a is installed
which po4a-translate > /dev/null 2>&1
if [ ! "x$?" = "x0" ]; then
    echo "Sorry, you need to install po4a first."
    exit 1
fi

# find the command number
NUM=0
find_num(){
    for i in 1 2 3 4 5 6 7 8 9;
    do
        # we assume if the po file exists, the man page exists
        po="po/${CMD}.${i}.zh_CN.po"
        if [ -e  "${po}" ];then
            eval "$1=$i"
            break
        fi
    done
}
find_num NUM

if [ $NUM = "0" ]; then
    printf "%s does not exist in this repo!\n" "${CMD}"
    exit
fi

po="po/${CMD}.${NUM}.zh_CN.po"
master="raw/man${NUM}/${CMD}.${NUM}"
target="/tmp/${CMD}.${NUM}"
printf "This is the original man page: %s\n" "${master}"

# regard fuzzy translations as translated
sed -e "s/fuzzy//g" "${po}" > /tmp/tmp.po

# generated the translated man page
po4a-translate -f man -m "${master}" -p /tmp/tmp.po -l /tmp/tmp.1
if [ ! -e /tmp/tmp.1 ]; then
    echo "Ooops, cannot generate the translated ${target}"
    exit
fi

# show this command in man browser
echo ". mso zh.tmac" > /tmp/ChineseSupport
cat /tmp/ChineseSupport /tmp/tmp.1 > "${target}"
man "${target}"
